### ISSUE TITLE
FilesystemDatastore Error

### ISSUE THREAD

**Issue by jbenet** [datastore/datastore#3]
There seems to be an error with `FilesystemDatastore`.

Consider:

``` python
>>> from datastore import *
>>> from datastore.impl.filesystem import FileSystemDatastore
>>> 
>>> fds = FileSystemDatastore('/tmp/dstest')
>>> fds.put(Key('/a/b/c:d'), '1')
>>> fds.get(Key('/a/b/c:d'))
'1'
>>> 
>>> list(fds.query(Query(Key('/a/b/c'))))
['1']
```

which all works fine. 

Instead of the expected:

``` python
>>> list(fds.query(Query(Key('/a'))))
[]
```

An error is caused:

``` python
>>> list(fds.query(Query(Key('/a'))))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/datastore/query.py", line 502, in next
    next = self._iterator.next()
  File "/Library/Python/2.7/site-packages/datastore/impl/filesystem.py", line 140, in _read_object_gen
    yield self._read_object(filename)
  File "/Library/Python/2.7/site-packages/datastore/impl/filesystem.py", line 130, in _read_object
    raise RuntimeError('%s is a directory, not a file.' % path)
RuntimeError: /tmp/dstest/a/a is a directory, not a file.
```

`FileSystemDatastore` should either ignore subdirectories in queries, or include them recursively. But certainly not cause an error.

**Comment by jbenet** [comment]
@ali01
